#server:
#port: 8080
spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://jpadb.c8zpd4vnux8w.ap-northeast-2.rds.amazonaws.com/jpadb?useSSL=false
    username: admin
    password: 20190976sswu

  jpa:
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false

  thymeleaf:
    cache: false

